engines:
  eslint:
    enabled: true
  duplication:
    enabled: true
    config:
      languages:
      - javascript
ratings:
  paths:
  - src/**
  - "**.js"

## other configuration excluded from example...
exclude_paths:
- "lib/"
- "build/"